#!/bin/sh

xrdb $HOME/.Xresources
xsetroot -solid grey
autocutsel -fork
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
export LC_ALL=C  # Corrected giant title bars; space for max character size?
#/etc/X11/Xsession

/usr/bin/jwm&
/usr/bin/xterm -geometry 80x25+0+0
